# Generated by Django 5.1.4 on 2025-01-06 08:32

import django.db.models.deletion
import django.utils.timezone
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        ('users', '0002_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('nationality', models.CharField(default='Ghanaian', max_length=50)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_phone_number', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_relationship', models.CharField(max_length=50)),
                ('previous_school', models.CharField(blank=True, max_length=255, null=True)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='admission_documents/', validators=[students.models.validate_file_extension, students.models.validate_file_size])),
                ('transcript', models.FileField(blank=True, null=True, upload_to='admission_documents/', validators=[students.models.validate_file_extension, students.models.validate_file_size])),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to='admission_documents/', validators=[students.models.validate_file_extension, students.models.validate_file_size])),
                ('program_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.parent'),
        ),
    ]
