# Generated by Django 5.1.4 on 2025-01-06 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_admissionapplication_student_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_confidential', models.BooleanField(default=True)),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'COUNSELOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='students.student')),
            ],
        ),
    ]
