# Generated by Django 5.1.4 on 2025-01-07 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Table',
                'verbose_name_plural': 'Custom Tables',
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('CharField', 'Text'), ('IntegerField', 'Integer'), ('DecimalField', 'Decimal'), ('BooleanField', 'Boolean'), ('DateField', 'Date'), ('DateTimeField', 'Date & Time')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='custom_tables.customtable')),
            ],
            options={
                'unique_together': {('table', 'name')},
            },
        ),
    ]
