# Generated by Django 5.1.4 on 2025-01-06 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grading_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.gradingscale'),
        ),
    ]
